# Adds a comment to all issues & PRs that were fixed on a new release
name: 💡 Update Issue after Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label-template: 🛩️ Released {release_tag}
          comment-template: |
            **This has now been released in {release_name} ✨**

            If you haven't done so already, please [update your instance](https://github.com/mlchain/mlchain/blob/master/docs/management.md#updating) to `{release_tag}` or later. See {release_link} for full info.
